platform :ios, :deployment_target => '5.0'
pod 'JSONKit'
pod 'AFNetworking' =>'1.3.2'
pod 'SSToolkit'
pod 'iCarousel'
pod 'SVProgressHUD'
pod 'MagicalRecord'
pod 'ECSlidingViewController'
pod 'AFOAuth2Client'
pod 'OpenUDID'
pod 'SVPullToRefresh'
pod 'Harpy'